/**
 * SECURITY: Schema-Based Input Validation Middleware
 * OWASP A03:2021 – Injection | A04:2021 – Insecure Design
 *
 * Uses Joi for declarative, schema-driven validation of all incoming request
 * bodies and Socket.io event payloads.
 *
 * Key security properties enforced by every schema:
 *  - Type checking   : strings must be strings, arrays must be arrays, etc.
 *  - Length limits   : upper bounds prevent memory exhaustion / log injection.
 *  - Pattern matching: emails and socket IDs validated against known formats.
 *  - Enum whitelists : only known enum values accepted (e.g. year, reason).
 *  - stripUnknown    : unrecognised fields are silently removed from the
 *                      validated object, preventing prototype-pollution payloads
 *                      and unexpected field injection (OWASP A08:2021).
 *  - abortEarly:false: all validation errors are collected in one pass so the
 *                      client gets a complete picture in one response.
 */

const Joi = require('joi');

// ─── Shared sub-schemas ────────────────────────────────────────────────────────

// University email: must end in a known academic TLD.
// The regex anchors at the start of the domain portion and is intentionally
// simple — the definitive domain check is done in auth.js (VALID_DOMAINS list).
const emailSchema = Joi.string()
    .email({ tlds: { allow: false } }) // Joi's email validator (RFC 5321-ish)
    .max(254)                           // RFC 5321 maximum email length
    .lowercase()
    .trim()
    .required();

// Password: at least 8 characters (NIST SP 800-63B minimum).
// Upper-bound of 128 chars prevents bcrypt DoS (bcrypt silently truncates at 72
// bytes in most implementations — the limit here adds a clear server-side guard).
const passwordSchema = Joi.string()
    .min(8)
    .max(128)
    .required();

// ─── REST endpoint schemas ────────────────────────────────────────────────────

/** POST /auth/register */
const registerSchema = Joi.object({
    name: Joi.string().trim().min(2).max(80).required(),
    email: emailSchema,
    password: passwordSchema,
    // university is optional at registration (can be set in profile later)
    university: Joi.string().trim().min(2).max(120).optional().allow(''),
}).options({ stripUnknown: true }); // SECURITY: silently drop unexpected fields

/** POST /auth/verify-otp */
const verifyOtpSchema = Joi.object({
    email: emailSchema,
    // OTP must be exactly 6 digits. String type required — do not accept
    // numeric values to prevent type-juggling issues in comparisons.
    otp: Joi.string()
        .pattern(/^\d{6}$/, '6-digit numeric OTP')
        .required(),
}).options({ stripUnknown: true });

/** POST /auth/login */
const loginSchema = Joi.object({
    email: emailSchema,
    // Max-length enforced to prevent bcrypt DoS even on the login path.
    password: Joi.string().max(128).required(),
}).options({ stripUnknown: true });

/** PUT /profile */
const YEAR_ENUM = ['1st Year', '2nd Year', '3rd Year', '4th Year', 'Masters', 'PhD'];

const profileUpdateSchema = Joi.object({
    name: Joi.string().trim().min(2).max(80).optional(),
    university: Joi.string().trim().min(2).max(120).optional(),
    major: Joi.string().trim().max(80).optional().allow(''),
    year: Joi.string().valid(...YEAR_ENUM).optional(),
    // Tags: array of non-empty strings, each max 30 chars, max 8 tags total.
    tags: Joi.array()
        .items(Joi.string().trim().min(1).max(30))
        .max(8)
        .optional(),
}).options({ stripUnknown: true });

/** POST /report */
// Reason is constrained to a whitelist — free-text reasons are NOT accepted
// here to prevent log injection through the reason field.
const REPORT_REASON_ENUM = [
    'inappropriate_content',
    'harassment',
    'spam',
    'underage',
    'hate_speech',
    'other',
];

// Socket IDs are alphanumeric strings generated by Socket.io.
// Pattern: letters, digits, underscores, hyphens — max 36 chars (UUID-ish).
const socketIdPattern = /^[a-zA-Z0-9_\-]{6,36}$/;

const reportSchema = Joi.object({
    reportedSocketId: Joi.string().pattern(socketIdPattern).required(),
    reason: Joi.string().valid(...REPORT_REASON_ENUM).required(),
    // reporterSocketId is optional (anonymous reports allowed).
    reporterSocketId: Joi.string().pattern(socketIdPattern).optional(),
}).options({ stripUnknown: true });

// ─── Socket event schemas ─────────────────────────────────────────────────────

/** join-queue payload */
const joinQueueSchema = Joi.object({
    mode: Joi.string().valid('random', 'campus', 'studybuddy', 'gaming', 'techtalk', 'ventroom').required(),
    userInfo: Joi.object({
        name: Joi.string().trim().min(1).max(80).optional().allow(''),
        university: Joi.string().trim().max(120).optional().allow(''),
        tags: Joi.array().items(Joi.string().trim().max(30)).max(8).optional(),
        major: Joi.string().trim().max(80).optional().allow(''),
        year: Joi.string().trim().max(30).optional().allow(''),
        showUniversity: Joi.boolean().optional(),
    }).optional(),
}).options({ stripUnknown: true });

/** send-message payload */
const sendMessageSchema = Joi.object({
    // 500 char max keeps logs manageable and matches UI limit.
    message: Joi.string().min(1).max(500).required(),
}).options({ stripUnknown: true });

/** leave-queue payload */
const leaveQueueSchema = Joi.object({
    mode: Joi.string().valid('random', 'campus', 'studybuddy', 'gaming', 'techtalk', 'ventroom').optional(),
}).options({ stripUnknown: true });

// ─── Express middleware factory ───────────────────────────────────────────────

/**
 * Returns an Express middleware that validates `req.body` against the given
 * Joi schema. On success, `req.body` is REPLACED with the validated (and
 * stripped) object so downstream handlers never see raw untrusted input.
 *
 * @param {Joi.Schema} schema
 * @returns {import('express').RequestHandler}
 */
function validateBody(schema) {
    return (req, res, next) => {
        const { error, value } = schema.validate(req.body, { abortEarly: false });

        if (error) {
            // Map Joi error details to human-readable messages.
            const messages = error.details.map((d) => d.message);
            return res.status(400).json({
                error: 'Validation failed.',
                // SECURITY: Return field-level errors to aid legitimate clients
                // but do NOT include the raw input value in error messages.
                details: messages,
            });
        }

        // Replace body with the sanitized, stripped value from Joi.
        req.body = value;
        next();
    };
}

/**
 * Validate a Socket.io event payload against a Joi schema.
 * Returns { valid: true, value } or { valid: false, errors: string[] }.
 * Callers should emit an 'error' event and return on failure.
 *
 * @param {Joi.Schema} schema
 * @param {unknown} data
 * @returns {{ valid: boolean, value?: object, errors?: string[] }}
 */
function validateSocketPayload(schema, data) {
    const { error, value } = schema.validate(data, { abortEarly: false });
    if (error) {
        return { valid: false, errors: error.details.map((d) => d.message) };
    }
    return { valid: true, value };
}

module.exports = {
    // Schemas (exported for use in tests)
    registerSchema,
    verifyOtpSchema,
    loginSchema,
    profileUpdateSchema,
    reportSchema,
    joinQueueSchema,
    sendMessageSchema,
    leaveQueueSchema,
    // Middleware factories
    validateBody,
    validateSocketPayload,
};
